# IstioOperator Configuration
# Version: 1.24.3
# Date: 2026-01-26
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-control-plane
  namespace: istio-system
spec:
  profile: default
  
  meshConfig:
    enableTracing: true
    accessLogFile: /dev/stdout
    
    extensionProviders:
      - name: jaeger
        opentelemetry:
          port: 4317
          service: jaeger.observability.svc.cluster.local
    
    defaultProviders:
      tracing:
        - jaeger
  
  components:
    base:
      enabled: true
    
    pilot:
      enabled: true
      k8s:
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
    
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          service:
            type: NodePort
            ports:
              - name: http2
                port: 80
                targetPort: 8080
                nodePort: 31080
              - name: https
                port: 443
                targetPort: 8443
                nodePort: 31443
    
    egressGateways:
      - name: istio-egressgateway
        enabled: false
  
  values:
    global:
      proxy:
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi
    
    pilot:
      traceSampling: 100.0
